name = "Juan Diaz"
rol = "Porn Star"
email = "daviidmdiaz@gmail.com"
phone = "+57 320 638 5425"
birthday = "February 17, 1996"
location = "Pasto, Nariño - Colombia"
avatar = "./config/assets/avatars/my-avatar.png"
username = "david-tm" # <-- github user name
googlemaps = "https://www.google.com/maps/place/Cl.+4+%2315-199,+Pasto,+Nari%C3%B1o/@1.2026335,-77.2864764,17z/data=!3m1!4b1!4m5!3m4!1s0x8e2ed49f9e4829dd:0x37396eda4c726f95!8m2!3d1.2026281!4d-77.2839015?entry=ttu" 
presentation = """
I'm Creative Director and UI/UX Designer from Sydney, Australia, working in web development and print media. I enjoy turning complex problems into simple, beautiful and intuitive designs.

My job is to build your website so that it is functional and user-friendly but at the same time attractive. Moreover, I add personal touch to your product and make sure that is eye-catching and easy to use. My aim is to bring across your message and identity in the most creative way. I created web design for many famous brand companies.
"""
 
